name: scrnaseq
channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - pip
  - python=3.10.10
  - r-base=4.3.1
  - r-curl=5.1.0
  - r-devtools=2.4.5
  - r-dplyr=1.1.3
  - r-igraph
  - r-leiden=0.4.3.1
  - r-matrix
  - r-openssl
  - r-readxl
  - r-reticulate=1.34.0
  - r-seurat=5.0.0
  - r-seuratobject=5.0.0
  - r-tidyverse=2.0.0
  - pip:
      - scanpy
      - leidenalg
      - scvi-tools
      - scvi-tools
      - scikit-misc 
